//
//  TorrentMigration.swift
//  iTorrent
//
//  Temporary compatibility migrations. Delete this file and its call sites
//  after the supported migration window has elapsed.
//

import Foundation
@preconcurrency import LibTorrent

enum TorrentMigration {
    static func prepareConfiguration(
        legacyURL: URL,
        destinationURL: URL
    ) -> URL {
        let activeURL = migrateConfigurationDirectory(
            from: legacyURL,
            to: destinationURL
        )
        migrateTorrentFileNames(at: activeURL)
        return activeURL
    }

    static func recoverDateAdded(
        in metadata: TorrentHandle.Metadata,
        from nativeDate: Date?,
        at url: URL
    ) -> TorrentHandle.Metadata {
        guard let nativeDate,
              metadata.dateAdded.timeIntervalSince(nativeDate) > 1
        else { return metadata }

        var recoveredMetadata = metadata
        recoveredMetadata.dateAdded = nativeDate
        if let data = try? JSONEncoder().encode(recoveredMetadata) {
            try? data.write(to: url, options: .atomic)
        }
        return recoveredMetadata
    }

    private static func migrateConfigurationDirectory(
        from legacyURL: URL,
        to destinationURL: URL
    ) -> URL {
        let fileManager = FileManager.default
        guard legacyURL != destinationURL,
              fileManager.fileExists(atPath: legacyURL.path())
        else { return destinationURL }

        do {
            try fileManager.createDirectory(at: destinationURL, withIntermediateDirectories: true)
            let sourceURLs = try fileManager.contentsOfDirectory(
                at: legacyURL,
                includingPropertiesForKeys: nil
            ).sorted { lhs, rhs in
                let lhsIsMetadata = lhs.pathExtension.lowercased() == "tmeta"
                let rhsIsMetadata = rhs.pathExtension.lowercased() == "tmeta"
                if lhsIsMetadata != rhsIsMetadata { return lhsIsMetadata }
                return lhs.lastPathComponent < rhs.lastPathComponent
            }

            for sourceURL in sourceURLs {
                let itemDestinationURL = destinationURL.appending(path: sourceURL.lastPathComponent)
                if fileManager.fileExists(atPath: itemDestinationURL.path()) {
                    if fileManager.contentsEqual(
                        atPath: sourceURL.path(),
                        andPath: itemDestinationURL.path()
                    ) {
                        continue
                    }

                    if sourceURL.pathExtension.lowercased() == "tmeta" {
                        // The old metadata is authoritative over files generated by a partial migration.
                        let metadata = try Data(contentsOf: sourceURL)
                        try metadata.write(to: itemDestinationURL, options: .atomic)
                    } else {
                        throw CocoaError(.fileWriteFileExists)
                    }
                } else {
                    try fileManager.copyItem(at: sourceURL, to: itemDestinationURL)
                }
            }

            try fileManager.removeItem(at: legacyURL)
            return destinationURL
        } catch {
            print("Failed to migrate torrent configuration: \(error)")
            return legacyURL
        }
    }

    private static func migrateTorrentFileNames(at directoryURL: URL) {
        let fileManager = FileManager.default
        guard let torrentURLs = try? fileManager.contentsOfDirectory(
            at: directoryURL,
            includingPropertiesForKeys: nil
        ).filter({ $0.pathExtension.lowercased() == "torrent" })
        else { return }

        for legacyURL in torrentURLs {
            guard let torrent = TorrentFile(with: legacyURL) else { continue }

            let canonicalURL = directoryURL
                .appending(path: torrent.infoHashes.best.hex)
                .appendingPathExtension("torrent")
            guard legacyURL.standardizedFileURL != canonicalURL.standardizedFileURL
            else { continue }

            do {
                if fileManager.fileExists(atPath: canonicalURL.path()) {
                    try fileManager.removeItem(at: legacyURL)
                } else {
                    try fileManager.moveItem(at: legacyURL, to: canonicalURL)
                }
            } catch {
                print("Failed to migrate torrent file \(legacyURL.lastPathComponent): \(error)")
            }
        }
    }
}
